Feature
amklass11/my-portfolio pull request #1
Opened 2022-02-17 11:59 UTC by amklass11

HTML STATIC SITE WAS BUILT IN ACCORDANCE WITH PROJECT  GUIDLINES 
1. NO LINTER ERRORS
2. GITFLOW APPROACH
3. NAV  BAR BUILT
4. MOBILE SKELETON  IMPLEMENTED 
5. BACKGROUND IMAGE ADDED
6. PAGE INTRO

2022-02-17 12:51 UTC, ShoiraTa commented
- [ ] The list of icons should use a `ul` tag to group them, and `li` per icon; each icon should have a link (`a` tag):
```
<ul>
   <li>
      <a href="#"><i class="fab fa-twitter"></i></a>
   </li>
</ul>
```

- [ ] Please make the style of icons and let's connect text meet the styles provided in Figma and add the missing icons:

 Figma design  | Your design
------------- | -------------
<img width="342" alt="Screenshot 2022-02-17 at 16 49 31" src="https://user-images.githubusercontent.com/77038610/154485087-6581c7a5-8381-46c6-8865-057798633c92.png"> | <img width="319" alt="Screenshot 2022-02-17 at 16 49 51" src="https://user-images.githubusercontent.com/77038610/154485141-37a51d5a-8935-45ed-b407-d97869022523.png">

2022-02-17 12:57 UTC, ShoiraTa requested changes
STATUS: CHANGES REQUIRED 🟡 
----
Hi @amklass11 , I’m Shoira, your reviewer for this PR :computer:,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 12:57 UTC, ShoiraTa commented on index.html
> +	<title>portfolio</title>
- [ ] I was happy to see your project so different from other projects, it is very creative and colorfull. But sadly, for this milestone you have to stick to figma design. You may wonder why do I have to do that 😄 , well because in the workplace you will requested to build projects based on templates. Therefor, lets try to make the design same as in Figma: 

Your design  | Figma design
------------- | -------------
<img width="321" alt="Screenshot 2022-02-17 at 16 33 39" src="https://user-images.githubusercontent.com/77038610/154482733-fa442a47-53cd-4ee8-870f-6596b4871b45.png"> | <img width="338" alt="Screenshot 2022-02-17 at 16 33 15" src="https://user-images.githubusercontent.com/77038610/154482676-379c7586-f4e0-47b2-b653-2289dfefd863.png">

MORE SPECIFICALLY: 

- [ ] Please make sure that the background is exactly the same (white with blue shapes, you can download them from figma), 
- [ ] Please make sure that you are using using the same font color, family and weight. In your case font family is `Poppins`. You can see all these details on the right side menu in Figma after clicking on the element.
<img width="673" alt="Screenshot 2022-02-17 at 16 38 24" src="https://user-images.githubusercontent.com/77038610/154483450-5ced25f4-859a-4d8d-aaa7-6319efd8bb75.png">
- [ ] Please make sure that the color of the logo and humburger bars are the same as in Figma (`#6070FF`)

2022-02-17 12:57 UTC, ShoiraTa commented on index.html
> +		<p>Dedicated to  bringing you the best that the world has to offer.
- [ ] Every page should have at least one `<h1>` tag. I recommend wrapping `AmkLass designs, Your Dream, Our Goal` text with `<h1>` tag

2022-02-17 12:57 UTC, ShoiraTa commented on index.html
> +		<div id="logo">AMKLASS</div>
- [ ] Logo is expected to be a link, where users can click and get to home page. Therefore I suggest you to wrap logo with `<a>` tag

2022-02-17 12:57 UTC, ShoiraTa commented on index.html
>  		<div id="social">
- [ ] The list of icons should use a `ul` tag to group them, and `li` per icon; each icon should have a link (`a` tag):
```
<ul>
   <li>
      <a href="#"><i class="fab fa-twitter"></i></a>
   </li>
</ul>
```

- [ ] Please make the style of icons and let's connect text meet the styles provided in Figma and add the missing icons:

 Figma design  | Your design
------------- | -------------
<img width="342" alt="Screenshot 2022-02-17 at 16 49 31" src="https://user-images.githubusercontent.com/77038610/154485087-6581c7a5-8381-46c6-8865-057798633c92.png"> | <img width="319" alt="Screenshot 2022-02-17 at 16 49 51" src="https://user-images.githubusercontent.com/77038610/154485141-37a51d5a-8935-45ed-b407-d97869022523.png">

2022-02-17 12:57 UTC, ShoiraTa commented on index.html
>  	<meta charset="utf-8">
- [ ] Please make your header take the full screen as provided in Figma: 

 Figma design  | Your design
------------- | -------------
<img width="342" alt="Screenshot 2022-02-17 at 16 54 34" src="https://user-images.githubusercontent.com/77038610/154485859-228e5949-c6c3-402e-bcc7-6148015ff26c.png">  | <img width="322" alt="Screenshot 2022-02-17 at 16 53 54" src="https://user-images.githubusercontent.com/77038610/154485751-1499daba-d564-4b4b-91df-034ff80a9685.png">

- [ ] Make sure that all the margins and paddings are the same.

2022-02-17 21:44 UTC, Deepakdanger requested changes
Hi @amklass11, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 21:44 UTC, Deepakdanger commented on index.html
> +			</ul>
- [ ]  As you have written very good code, but there is little difference in the color of icons please fix that.
- Your design 
![v bv](https://user-images.githubusercontent.com/26767383/154573551-c2c76f87-69f5-45a5-8420-324fd497e992.PNG)

- Original design
![hgcbv](https://user-images.githubusercontent.com/26767383/154573786-f1fe8230-5826-46e0-8e0d-b1a3c54ffbd1.PNG)

2022-02-17 21:44 UTC, Deepakdanger commented on index.html
>  	<header>
- [ ] The `background image` should be the same as the original website, Fix fix that, As requested by the previous reviewer.
- Original website 
![b bn](https://user-images.githubusercontent.com/26767383/154575020-f0836f30-916c-477e-b870-f256d7c1e954.PNG)
- Your website

![hjvjhg](https://user-images.githubusercontent.com/26767383/154575139-11d560fd-773f-429d-b863-0bafe44f56c8.PNG)

2022-02-18 07:02 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @amklass11 ,  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
- Project is set up correctly ✔️ 
- Descriptive Pull Request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 07:02 UTC, ShoiraTa commented on index.html
> +		<h1>I'm Mariane, Glad to meet you</h1>
- [ ] OPTIONAL:  Currently the font family is Sans serif, please make sure that you use `Poppins` font family as provided in Figma 😉. 

- [ ] OPTIONAL: The header looks too dark and black, I recommend you to change color to `#172B4D` which is milder black

2022-02-18 07:02 UTC, ShoiraTa commented on index.html
> +			U dream it We Build it:) </p>
- [ ] OPTIONAL:  Currently the font family is Sans serif, please make sure that you use `Poppins` font family as provided in Figma 😉. 

- [ ] OPTIONAL: The paragraph looks too dark and black, I recommend you to change color to `#344563` which is milder black

2022-02-18 08:33 UTC, merged